"""new fields in user model

Revision ID: 295d71b7801b
Revises: 0b8bc2ff13bf
Create Date: 2020-03-12 19:02:59.390336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295d71b7801b'
down_revision = '0b8bc2ff13bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
